#######################
### APP KEYBINDINGS ###
#######################

bind = SUPER, return, exec, $terminal
bind = SUPER, SPACE, exec, $menu
bind = SUPER SHIFT, O, exec, obsidian 
bind = SUPER ALT, SPACE, exec, pkill rofi || ~/.config/waybar/scripts/sysmenu.sh
bind = SUPER SHIFT, F, exec, $fileManager
bind = SUPER SHIFT, B, exec, $browser


