#######################
### APP KEYBINDINGS ###
#######################

#rofi
bind = SUPER ALT, SPACE, exec, pkill rofi || ~/.config/waybar/scripts/sysmenu.sh # start menu
bind = SUPER, SPACE, exec, $menu
bind = SUPER SHIFT, V, exec, pkill rofi || /home/leabua/.dotfiles/scripts/cliphist-rofi
bind = SUPER SHIFT, C, exec, pkill rofi || /home/leabua/.dotfiles/scripts/cliphist-rofi

# wallpaper switcher
bind = SUPER SHIFT, P, exec, ~/.dotfiles/scripts/rotate_wallpaper.sh

# generics that can be found in hyprland.conf. 
# These have to be loaded in before the sources, hence why they are not in here.

bind = SUPER, return, exec, $terminal
bind = SUPER SHIFT, O, exec, obsidian 
bind = SUPER SHIFT, F, exec, $fileManager
bind = SUPER SHIFT, B, exec, $browser

