##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# All of the below work through the waybar
# audio tui window hover rules -> left click audio icon
windowrule {
    name = wiremix-float
    # this matches the --title we set in waybar
    match:title = ^wiremix-term$
    match:class = com.mitchellh.ghostty
    float = yes
    # Increase the first number to push it right
    # Decrease the second number to push it up
    move = 1307 51 
    size = 600 400
}

#bluetooth tui hover rules -> right click audio icon
windowrule {
    name = bluetui-float
    # this matches the --title we set in waybar
    match:title = ^bluetui-term$
    match:class = com.mitchellh.ghostty
    float = yes
    # Increase the first number to push it right
    # Decrease the second number to push it up
    move = 1307 51 
    size = 600 800
}

# wifi tui hover rules -> left click wifi toggle
windowrule {
    name = impala-float
    # this matches the --title we set in waybar
    match:title = ^impala-term$
    match:class = com.mitchellh.ghostty
    float = yes
    # Increase the first number to push it right
    # Decrease the second number to push it up
    move = 1307 51 
    size = 600 800
}

# System Menu TUI Rules (Pacseek, PWA, Yazi)
windowrule {
    name = sysmenu-floating-tui
    match:title = ^sysmenu-tui$
    match:class = com.mitchellh.ghostty
    float = yes
    center = yes
    size = 900 600
}

windowrule {
    name = localsend-float
    match:class = ^localsend$
    float = yes
    center = yes
    size = 900 600
}
