# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- alacritty --working-directory "$(omarchy-cmd-terminal-cwd)"
# bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- ghostty
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT, L, LocalSend, exec, uwsm-app -- localsend --new-window
bindd = SUPER SHIFT, B, Helium, exec, omarchy-launch-or-focus ^helium$ "uwsm-app -- helium-browser"
# bindd = SUPER SHIFT, B, Zen, exec, omarchy-launch-or-focus ^zen$ "uwsm-app -- zen-browser"
bindd = SUPER SHIFT, M, Apple Music, exec, omarchy-launch-or-focus ^chrome-music.apple.com__-Default$ "uwsm-app -- /usr/bin/chromium --profile-directory=Default --app-id=blgdilankhbcpipclgpdndahbehalgkh --app=https://music.apple.com"

# Forcing the screensaver
bindd = SUPER SHIFT, S, Screensaver, exec, omarchy-launch-screensaver

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

