###################
### MY PROGRAMS ### <- This must always be at the very top of the file. Otherwise binds will silently fail.
###################
# See https://wiki.hypr.land/Configuring/Keywords/
# Set programs that you use
$browser = helium-browser
$fileManager = nautilus
$menu = pkill -x rofi || rofi -show drun -theme ~/.config/rofi/config.rasi
$terminal = ghostty

####################
### SOURCE FILES ### <- Programs must always come before this otherwise binds dont work
####################

# Source files
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/bindings.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/looknfeel.conf
source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/tiling.conf
source = ~/.config/hypr/modules/utilities.conf
source = ~/.config/hypr/modules/windowrules.conf

# See https://wiki.hypr.land/Configuring/Environment-variables/

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
