# --- Sourced Theme ---
source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 2
}

# --- Circular Profile Photo ---
image {
    monitor =
    path = /home/leabua/Documents/Wallpapers/cute_profiles.jpeg
    size = 230
    rounding = -1
    border_size = 4
    border_color = $outer_color
    rotate = 0
    reload_time = -1
    position = 0, 70
    halign = center
    valign = center
    zindex = 10
}

# --- Password Input ---
input-field {
    monitor =
    size = 300, 55
    position = 0, -100
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 3

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 12
    shadow_passes = 0
    fade_on_empty = false
    zindex = 10
}

auth {
    fingerprint:enabled = true
}
