# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  # Hardware detection: import support for devices discovered during installation.
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Kernel: early-boot storage drivers and Intel virtualization support.
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Filesystems: root partition and EFI system partition.
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ca2a3c59-2a27-40f5-8d78-5e7be2c1855a";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D752-8D19";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # Swap: disk-backed swap used alongside the configured zram device.
  swapDevices = [
    { device = "/dev/disk/by-uuid/108fadf6-d47f-4d50-8cae-f9c459872dfc"; }
  ];

  # Platform and firmware: host architecture and Intel microcode updates.
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
