# Prefix
# set -g prefix C-Space
# unbind C-b
# bind C-Space send-prefix

# If I close the last tmux session it wont just hang around with an empty pane.
set -g detach-on-destroy on

# Mouse support
set -g mouse on

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# Easier splits
unbind %
unbind '"'
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# True colour
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"

# Clean status bar
set -g status-position bottom
set -g status-style "bg=default"
set -g status-right ""
set -g status-left "#[bg=colour4,fg=colour16] #S "
set -g window-status-format "#[fg=colour8] #I #W "
set -g window-status-current-format "#[bg=colour2,fg=colour16] #I #W #[bg=default,fg=colour2]"
set -g status-left-length 10

#alt hjkl navigation between panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Switch windows using Alt + number without prefix
bind -n M-0 select-window -t 0
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9


# Adding tmux continuum and resurrect to the mix
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Continuum settings (optional but recommended)
set -g @continuum-restore 'on'  # Auto-restore sessions on tmux start
set -g @continuum-save-interval '10'  # Auto-save every 15 minutes

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
